"""empty message

Revision ID: 04be4bd6fec7
Revises: bcba31c58c7d
Create Date: 2023-07-29 13:20:11.076160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04be4bd6fec7'
down_revision = 'bcba31c58c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=True)

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats', sa.String(length=64), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('seats')

    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
