"""empty message

Revision ID: 058f1299f0d2
Revises: 
Create Date: 2023-07-29 20:00:37.282234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058f1299f0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=7), nullable=True),
    sa.Column('end_time', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('number_of_guests', sa.Integer(), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('tableid', sa.Integer(), nullable=True),
    sa.Column('slotid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slotid'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['tableid'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('tables')
    op.drop_table('slots')
    # ### end Alembic commands ###
