"""empty message

Revision ID: 56c715883e8b
Revises: 04be4bd6fec7
Create Date: 2023-07-29 13:32:32.768471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c715883e8b'
down_revision = '04be4bd6fec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_constraint('slots_tableid_fkey', type_='foreignkey')
        batch_op.drop_constraint('slots_bookingid_fkey', type_='foreignkey')
        batch_op.drop_column('tableid')
        batch_op.drop_column('bookingid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tableid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('slots_bookingid_fkey', 'bookings', ['bookingid'], ['id'])
        batch_op.create_foreign_key('slots_tableid_fkey', 'tables', ['tableid'], ['id'])

    # ### end Alembic commands ###
