"""empty message

Revision ID: 7e8b65e2e1ee
Revises: 058f1299f0d2
Create Date: 2023-07-30 23:14:46.178805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e8b65e2e1ee'
down_revision = '058f1299f0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('booking_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###
