"""empty message

Revision ID: bcba31c58c7d
Revises: eb15eb449500
Create Date: 2023-07-29 13:04:51.098930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcba31c58c7d'
down_revision = 'eb15eb449500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingid', sa.Integer(), nullable=True),
    sa.Column('tableid', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookingid'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['tableid'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('slot')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tableid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slotid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'slots', ['slotid'], ['id'])
        batch_op.create_foreign_key(None, 'tables', ['tableid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('slotid')
        batch_op.drop_column('tableid')
        batch_op.drop_column('accepted')
        batch_op.drop_column('phone_number')

    op.create_table('slot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bookingid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tableid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookingid'], ['bookings.id'], name='slot_bookingid_fkey'),
    sa.ForeignKeyConstraint(['tableid'], ['tables.id'], name='slot_tableid_fkey'),
    sa.PrimaryKeyConstraint('id', name='slot_pkey')
    )
    op.drop_table('slots')
    # ### end Alembic commands ###
