"""empty message

Revision ID: e388bcd5e9b8
Revises: f10dca67e065
Create Date: 2023-07-29 12:48:22.102322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e388bcd5e9b8'
down_revision = 'f10dca67e065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingid', sa.Integer(), nullable=True),
    sa.Column('bableid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bableid'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['bookingid'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    # ### end Alembic commands ###
