"""empty message

Revision ID: f10dca67e065
Revises: d5380c3e1b07
Create Date: 2023-07-29 12:46:28.407441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10dca67e065'
down_revision = 'd5380c3e1b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint('tables_booking_id_fkey', type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tables_booking_id_fkey', 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###
